-- ===========================
--  SCHEMA MIGRATION (Flyway)
--  Generated from postgres dump
-- ===========================

-- HUMEDAL
CREATE TABLE IF NOT EXISTS humedal (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       descripcion_corta VARCHAR(500),
    descripcion_larga VARCHAR(2000),
    imagen_principal VARCHAR(255),
    mapa_url VARCHAR(1000),
    nombre VARCHAR(255) NOT NULL,
    subtitulo VARCHAR(255),
    ubicacion VARCHAR(255)
    );

-- HUMEDAL GALERIA
CREATE TABLE IF NOT EXISTS humedal_galeria (
                                               humedal_id BIGINT NOT NULL,
                                               imagen_url VARCHAR(255),
    CONSTRAINT fk_humedal_galeria_humedal
    FOREIGN KEY (humedal_id)
    REFERENCES humedal(id)
    );

-- ESPECIE
CREATE TABLE IF NOT EXISTS especie (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       descripcion VARCHAR(1000),
    estado_conservacion VARCHAR(255),
    imagen_url VARCHAR(255),
    nombre_cientifico VARCHAR(255),
    nombre_comun VARCHAR(255),
    tipo VARCHAR(255),
    humedal_id BIGINT,
    CONSTRAINT especie_estado_conservacion_check CHECK (
                                                           estado_conservacion IN ('LC','NT','VU','EN','CR','EW','EX','DD')
    ),
    CONSTRAINT especie_tipo_check CHECK (
                                            tipo IN ('FLORA','FAUNA')
    ),
    CONSTRAINT fk_especie_humedal
    FOREIGN KEY (humedal_id)
    REFERENCES humedal(id)
    );

-- TESTIMONIO
CREATE TABLE IF NOT EXISTS testimonio (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          autor VARCHAR(255),
    fecha DATE,
    texto VARCHAR(1000),
    humedal_id BIGINT,
    CONSTRAINT fk_testimonio_humedal
    FOREIGN KEY (humedal_id)
    REFERENCES humedal(id)
    );

-- USERS
CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     password VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL UNIQUE
    );
